mothership-ec/cog-mothership-cms

resources/view/search/listing.html.twig
src/Controller/Frontend.php

The minimum character limit was set to 4 when searching through the front end, although there was a config setting for this already. This PR undoes that, and also deletes a bunch of commented out code
Yes. This change isn't a BC break, but making this change did break a Mothership site with a view override on the search listing. Reason being that the ternary operator that checks the slug length wasn't there:
```twig
{% set url = url('ms.cms.frontend', {slug: page.slug ?: '/' |trim('/')}) %}
```

Reverted front end search character limit to char limit set in config

---

src/Bootstrap/Tasks.php
src/Controller/ControlPanel/Edit.php
src/Page/Loader.php
src/Task/FixPageTree.php

Adds a task to fix the nested set tree structure if something bad happens to the data. It also changes the loader to check for the unpublished page with the lowest position_left to use as the homepage instead of `left == 1`.

Fix page ordering

---

resources/assets/js/page-edit.js
resources/view/edit.html.twig
src/Controller/ControlPanel/Edit.php
src/Page/Edit.php
src/Page/Exception/PageEditException.php
translations/en.yml

This pull request has been created as a result of the damage done to data by saving a sibling and parent to a page that are no valid with each other. This adds tighter validation and error reporting, and prevents users from being able to do this.
Requires https://github.com/mothership-ec/cog/pull/431
+ Catches `NestedSetExceptions` informing the user that their data is malformed and they will need to seek assistance from their web developer
+ Adds PageEditException
+ `changeParent()` and `changeOrder()` methods on `Page\Edit` return false if `Transaction::commit()` 
+ `changeOrder()` throws `PageEditException` if no page sibling can be found
+ `PageEditException` caught by attribute edit action
+ JavaScript to disable `Siblings` field on attributes edit screen if the parent has changed

Check for and prevent malformed data when moving pages

---

CHANGELOG.md
resources/view/modules/dashboard/comments.html.twig
src/Blog/Comment.php
src/Blog/CommentBuilder.php
src/Blog/CommentLoader.php
src/Blog/Dashboard/DashboardLoader.php
src/Bootstrap/Services.php
src/Controller/Module/Dashboard/BlogComments.php
src/Controller/Module/Dashboard/CMSSummary.php
src/EventListener.php
translations/en.yml

Adds a dashboard widget showing basic information about comments. It will do the following:
+ Only show up if there is a page type that extends `AbstractBlog` 
+ Will display a list of pages that have comments with a status of `pending`
+ Will display a list of pages that have comments that have been approved within the last 7 days
+ All pages that appear in lists will have links to view the page, and to review the comments
Additional functionality:
+ Automatic comment approval for super admins
+ Added `getUpdatedAt()` method to Comment object
+ Added `getByStatus()` method to `CommentLoader`
Potential BC break:
+ The `CommentBuilder` class has had an extra parameter added to its __construct() method. I figure this is fairly safe since the number of people use Mothership is still low, …

Blog comments dashboard widget

---

resources/fixtures/config/social.yml
resources/view/modules/social/links.html.twig

I spelt pinterest wrong in a couple of places. Fixes for that.

Pinterest spelt wrongly

---

resources/fixtures/config/social.yml

We don't really want these to be in skel's cofig dir because it makes setup confusing as hell.

Mothership defaults to social config

---

translations/en.yml

Adds image translation to the cms translations file.
Remove this translation from a site; the blog image translation (when expanded) will be broken; switch to this branch; it will be fixed.

Add image translation for blog

---

composer.json
composer.lock
readme.md
resources/assets/js/filter-pages.js
resources/view/modules/filter_form.html.twig
src/Bootstrap/Services.php
src/Controller/ControlPanel/Edit.php
src/Controller/Module/PageFilter.php
src/Form/RangeFilterForm.php
src/Page/Filter/AbstractContentFilter.php
src/Page/Filter/ContentFilter.php
src/Page/Filter/ContentFilterInterface.php
src/Page/Filter/ContentRangeFilter.php
src/Page/Filter/README.md
src/Page/Filter/TagFilter.php
src/Page/Loader.php
src/Page/TagLoader.php
translations/en.yml

This PR implements page filtering functionality using the new Filter component in Cog (https://github.com/mothership-ec/cog/pull/440)
A side effect of this is a total overhaul of the page loader to use the QueryBuilder instead of straight up queries, which is a refactor that has been on the cards for a long time coming
+ `Page\Filter` namespace
+ `TagFilter` class for filtering pages by their tags
+ `ContentFilter` class for filtering by content fields
+ `ContentRangeFilter` class for filtering for pages with content that falls between two values
+ `ContentFilterInterface` interface for classes that filter by content, implemented by `ContentFilter` and `ContentRangeFilter`
+ `AbstractContentFilter` abstract class extended by `ContentFilter` and `ContentRangeFilter`
+ `RangeFilterForm` …

Page Filtering (and Page\Loader refactor)

---

src/Form/RangeFilterForm.php

This PR adds options to add placeholders to the `RangeFilterForm` fields by adding `min_placeholder` and `max_placeholder` options

added placeholders to range filter form

---

src/Page/Loader.php

`getAll()` on the page loader wasn't set to return as an array, so if only one page existed the sidebar would break in the CMS

getAll() method on page loader returns as array

---

src/Page/Loader.php

`$page->depth` gets bound from mysql as a String when loaded (if the mysqlnd ext is not installed). This was causing this check to fail. Fixes #264.

Get siblings soft depth check

---

resources/fixtures/config/social.yml
resources/view/modules/social/links.html.twig
resources/view/modules/social/share.html.twig
src/Controller/Module/Social.php
src/Page/Loader.php

This adds a social link for Tumblr and Share links for both Tumblr and Pinterest as well as a way to specify which share links to display. The shown share links defaults to Twitter and Facebook to preserve BC.
To test try calling
```
{{
render(controller('Message:Mothership:CMS::Controller:Module:Social#share', {
page: page,
networks: ['facebook', 'twitter', 'pinterest', 'tumblr']
}))
}}
```
and checking the links that come out.
Also test the tumblr link.

Social links for tumblr and pinterest

---

src/Controller/ControlPanel/Edit.php
src/Page/Edit.php

When editing a page attributes, the access groups were being set as strings. In all other cases where the page is being saved (content etc) the access groups are access objects. This is how the Loader loads them and how they should be. The Edit class was also expecting the attributes to be of type string (as that is what the action was passing it) therefore calling save() on a page without changing the array of access objects to an array of strings would break on the access query (cannot cast object to string).
To test try changing the title of a page which has access groups set. Try setting and unsetting access groups.

Page edit access bug

---

src/Page/TagLoader.php

This PR adds a method that allows us to load tags for any children of a given page, specifically to be used when filtering by tag

Added getTagsFromChildren() method to TagLoader

---

src/Page/Loader.php

See issue #269 for a description of the problem.
Test by calling something like this in a controller:
```php
$pagination = $this->get('pagination');
$loader = $this->get('cms.page.loader')->setPagination($pagination);
$loader->getByID([]);
$pagination->getCount();
```
Prior to the changes, there would be a horrid exception thrown.

Set pagination count query if loader returns early

---

src/Page/PageProxy.php

Tags weren't appearing in the attributes tab for unpublished pages, meaning that it looked like they weren't saving even though they were. This PR sets tags to always load if via a page proxy, regardless of whether the page is unpublished or deleted.

Set tag loader on page proxy to include unpublished and deleted

---

src/Controller/Frontend.php

If the homepage is redirected to via slug_history, it was breaking due to redirecting to an empty slug. To fix this it now should redirect to '/' if it is the homepage.
Try adding a redirect to a homepage and going there. It should redirect properly.

Frontend redirects to homepage properly

---

CHANGELOG.md
composer.json
composer.lock
src/Bootstrap/Services.php
src/FieldType/Link.php
src/Page/Loader.php
src/Page/PageCollection.php

This adds a PageCollection and the "cms.page.cache" service. This reduces the number of queries and memory usage by a lot in places where the pages are all loaded in multiple time (for instance when editing a PageType with multiple Link fields).
This requires https://github.com/mothership-ec/cog/pull/458.

Added the page cache to PageLoader

---

resources/assets/js/filter-pages.js

This allows users to define an ajax filter using `filterPages('{{ page.slug }}', '#product-listing');`, no extra routes required. It tests to see if the listing element exists within the result, and if so, just uses that element. Otherwise it uses the whole response.
This means that the route can be set to the current pages slug to use the current location. Test on with the extra route way as well as the page route way to check for BC breaks.

Filters: Try to replace with the element rather than the whole screen

---

resources/assets/js/filter-pages.js

This replaces the inner of the filter element with the inner of the new filter element rather than replacing the inner of the element with the entire new element. This is to avoid duplicate nested filter elements.

Replace filters with children of replcement element

---

src/Page/Loader.php

Page access groups were not loading on properly and we kept getting an error on the attributes page. This tests the access to see if it's set to an array.
Make sure this makes that error goes away.

Added a better test to see if access is loaded

---

src/Page/ContentEdit.php
src/Page/Event/ContentEvent.php

This PR ensures that an event is fired upon page load. It extends the Page event so it can also be used by methods that use them

Add contentevent and dispatch it on content edit

---

src/FieldType/Link.php
src/Page/Page.php

This PR adds an `isPublished()` method to the page object, and prevents deleted pages from showing up in the link field. It also marks unpublished pages as unpublished when using the link field in CMS mode

Added `isPublished()` method, do not include deleted pages on link field

---

src/Page/Filter/ContentFilter.php

This PR prevents content filters from loading content from deleted or unpublished pages when setting the choices. This could be perceived as a behavioural change but I'm willing to call the original behaviour as a bug as I can't see any reason why you would this data to be loaded into the choices, so don't think it's worth making it a configurable

Do not include unpublished or deleted page in content filters

---

src/Page/Loader.php

Fixes the loadFromFilters method. It was throwing an exception as the _buildQuery method had not been run.
Test this function with some filters.

Fixed loadFromFilter() on page loader

---

composer.json
composer.lock
src/Bootstrap/Services.php
src/Controller/ControlPanel/Edit.php
src/Page/Edit.php
src/Page/Exception/SlugUpdateException.php
src/Page/Loader.php
src/Page/SlugEdit.php
translations/en.yml

This PR stabilises slug updating when editing a page.
Changes in this PR:
+ Moved slug update code from controller to new `Page\SlugEdit` class and split it out into methods
+ Added `Page\Exception\SlugUpdateException` which extends the new `TranslationLogicException` to send translation strings to the controller to render as flash messages
+ It is now possible to update slugs that are set against deleted pages without being informed
Requires https://github.com/mothership-ec/cog/pull/478

Refactor slug updating

---

src/Exception/HistoricalSlugExistsException.php
src/Page/SlugGenerator.php

Saving pages with a name that would cause it to be generated with a historical slug would error. This exception is unnecessary I think and this feature hinders usability.
Currently this still appends a number to the end of the slug if it exists as a historical slug, do you think it should remove the existing slug or work in the same way as it does currently. I'm of the opinion that if a page has been renamed, we don't need to be too precious about its old slug,

Deprecate HistoricalSlugExistsException, and remove from SlugGenerator

---

resources/view/modules/social/share.html.twig

Adds email share link. This doesn;t require any config setup, however to make it show, it must be called in the networks array.

Added email share link
